### ISSUE TITLE
Install succeeds but doesn't appear in list

### ISSUE THREAD

**Issue by ghost** [SergeoLacruz/inventree-supplier-panel#2]
I installed the plugin but I don't see any trace of a configuration for it.

Here is the install log output:
```Collecting git+https://github.com/SergeoLacruz/inventree-supplier-panel
  Cloning https://github.com/SergeoLacruz/inventree-supplier-panel to /tmp/pip-req-build-blcoabey
  Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-blcoabey
  Resolved https://github.com/SergeoLacruz/inventree-supplier-panel to commit 2f743b6efd1bcfc617a9679bc10addc54f855a6a
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: inventree-supplier-panel
  Building wheel for inventree-supplier-panel (setup.py): started
  Building wheel for inventree-supplier-panel (setup.py): finished with status 'done'
  Created wheel for inventree-supplier-panel: filename=inventree_supplier_panel-0.0.2-py3-none-any.whl size=8780 sha256=27e027413c0249b6a2c5b378b4cb1e3a604241db346b881706a5ca93d340d161
  Stored in directory: /tmp/pip-ephem-wheel-cache-jy7tf26q/wheels/b7/3a/a3/ab2dbc1b26e84d3aca3bc80319a26836d9a38213714b15985f
Successfully built inventree-supplier-panel
Installing collected packages: inventree-supplier-panel
Successfully installed inventree-supplier-panel-0.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Logs from 6/8/2023, 9:30:18 PM
```

Here are the contents of the plugins.txt file after the install:
```
cat data/plugins.txt 
# InvenTree Plugins (uses PIP framework to install)

-i https://github.com/SergeoLacruz/inventree-supplier-panel inventree-supplier-panel  # Installed 2023-06-09 03:01:49.524246+00:00 by caleb
```

Here is the image showing that only the default plugins are available:

![image](https://github.com/SergeoLacruz/inventree-supplier-panel/assets/116731/40f0faae-1ce5-41e6-ab5a-ec766096d20a)

Can someone please assist me with this? My company would really love to use this plugin!

**Comment by SergeoLacruz** [comment]
Did you activate it in the admin area?MichaelAm 09.06.2023 um 05:55 schrieb sillydino ***@***.***>:﻿
I installed the plugin but I don't see any trace of a configuration for it.
Here is the install log output:
  Cloning https://github.com/SergeoLacruz/inventree-supplier-panel to /tmp/pip-req-build-blcoabey
  Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-blcoabey
  Resolved https://github.com/SergeoLacruz/inventree-supplier-panel to commit 2f743b6efd1bcfc617a9679bc10addc54f855a6a
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: inventree-supplier-panel
  Building wheel for inventree-supplier-panel (setup.py): started
  Building wheel for inventree-supplier-panel (setup.py): finished with status 'done'
  Created wheel for inventree-supplier-panel: filename=inventree_supplier_panel-0.0.2-py3-none-any.whl size=8780 sha256=27e027413c0249b6a2c5b378b4cb1e3a604241db346b881706a5ca93d340d161
  Stored in directory: /tmp/pip-ephem-wheel-cache-jy7tf26q/wheels/b7/3a/a3/ab2dbc1b26e84d3aca3bc80319a26836d9a38213714b15985f
Successfully built inventree-supplier-panel
Installing collected packages: inventree-supplier-panel
Successfully installed inventree-supplier-panel-0.0.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Logs from 6/8/2023, 9:30:18 PM

Here are the contents of the plugins.txt file after the install:
cat data/plugins.txt 
# InvenTree Plugins (uses PIP framework to install)

-i https://github.com/SergeoLacruz/inventree-supplier-panel inventree-supplier-panel  # Installed 2023-06-09 03:01:49.524246+00:00 by caleb

Here is the image showing that only the default plugins are available:

Can someone please assist me with this? My company would really love to use this plugin!

**Comment by ghost** [comment]
It does not appear in the admin area either:

![image](https://github.com/SergeoLacruz/inventree-supplier-panel/assets/116731/7763cb72-e0ef-453d-9730-52fc160ed5d4)

**Comment by SergeoLacruz** [comment]
Strange. Unfortunately I can’t have look because I am on vacation for two more weeks. Will take some timeMichaelAm 09.06.2023 um 14:16 schrieb sillydino ***@***.***>:﻿
It does not appear in the admin area either:

**Comment by ghost** [comment]
Thanks!

**Comment by roman-dvorak** [comment]
Hi, it behaves the same way for me. Obviously, the entire plugin will not be installed during the timeout. 
I have obtained same information about successful installation in web UI. 

In file `plugins.txt` it is correctly added:
```
  GNU nano 5.4                                                                           ../inventree-data/plugins.txt                                                                                     
# InvenTree Plugins (uses PIP framework to install)

git+https://github.com/SergeoLacruz/inventree-supplier-panel  # Installed 2023-07-03 21:09:55.212697+00:00 by roman
```

In console output (after server start-up) of Inventreee-server I can see this:

<pre><font color="#26A269">inventree-server  | </font>[2023-07-03 21:17:34 +0000] [9] [WARNING] Worker with pid 13 was terminated due to signal 9
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:17:34 +0000] [9] [WARNING] Worker with pid 11 was terminated due to signal 9
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:17:34 +0000] [9] [WARNING] Worker with pid 10 was terminated due to signal 9
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:17:34 +0000] [9] [WARNING] Worker with pid 12 was terminated due to signal 9
<font color="#A347BA">inventree-worker  | </font>  Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-cf8np576
<font color="#26A269">inventree-server  | </font>  Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-60gfodo4
<font color="#26A269">inventree-server  | </font>  Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-g340tzvo
<font color="#26A269">inventree-server  | </font>  Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-a55bv1on
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:242)
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:243)
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:244)
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:245)
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:06 +0000] [9] [WARNING] Worker with pid 243 was terminated due to signal 9
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:06 +0000] [9] [WARNING] Worker with pid 242 was terminated due to signal 9
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:06 +0000] [9] [WARNING] Worker with pid 244 was terminated due to signal 9
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:06 +0000] [9] [WARNING] Worker with pid 245 was terminated due to signal 9
<font color="#A2734C">inventree-proxy   | </font>2023/07/03 21:18:26 [error] 21#21: *23 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.165, server: , request: &quot;GET /settings/ HTTP/1.1&quot;, upstream: &quot;http://172.18.0.3:8000/settings/&quot;, host: &quot;astrometerspi.lan:1337&quot;, referrer: &quot;http://astrometerspi.lan:1337/stock/item/12/&quot;
<font color="#A2734C">inventree-proxy   | </font>192.168.1.165 - - [03/Jul/2023:21:18:26 +0000] &quot;GET /settings/ HTTP/1.1&quot; 504 167 &quot;http://astrometerspi.lan:1337/stock/item/12/&quot; &quot;Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0&quot; &quot;-&quot;
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:457)
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:459)
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:460)
<font color="#26A269">inventree-server  | </font>[2023-07-03 21:18:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:461)
</pre>


I have tried to extend timeout time in config.yaml file. But Timeout occurs in the same time. This setting (in config.yaml) has no effect on the workers timeout. Do you know, how to extend this timeout? 

It seems that actual timeout is something around 30s. In config.yaml is pre-set value 90. I think that it can take longer time to install this pip plugin and satisfy all other requirements. Especially on new installations.

**Comment by SergeoLacruz** [comment]
Did you try to install it from the command line?Am 03.07.2023 um 23:33 schrieb Roman Dvořák ***@***.***>:﻿
Hi, it behaves the same way for me. Obviously, the entire plugin will not be installed during the timeout.
In file plugins.txt it is correctly added:
  GNU nano 5.4                                                                           ../inventree-data/plugins.txt                                                                                     
# InvenTree Plugins (uses PIP framework to install)

git+https://github.com/SergeoLacruz/inventree-supplier-panel  # Installed 2023-07-03 21:09:55.212697+00:00 by roman

In console output (after server start-up) of Inventreee-server I can see this:
inventree-server  | [2023-07-03 21:17:34 +0000] [9] [WARNING] Worker with pid 13 was terminated due to signal 9
inventree-server  | [2023-07-03 21:17:34 +0000] [9] [WARNING] Worker with pid 11 was terminated due to signal 9
inventree-server  | [2023-07-03 21:17:34 +0000] [9] [WARNING] Worker with pid 10 was terminated due to signal 9
inventree-server  | [2023-07-03 21:17:34 +0000] [9] [WARNING] Worker with pid 12 was terminated due to signal 9
inventree-worker  |   Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-cf8np576
inventree-server  |   Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-60gfodo4
inventree-server  |   Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-g340tzvo
inventree-server  |   Running command git clone --filter=blob:none --quiet https://github.com/SergeoLacruz/inventree-supplier-panel /tmp/pip-req-build-a55bv1on
inventree-server  | [2023-07-03 21:18:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:242)
inventree-server  | [2023-07-03 21:18:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:243)
inventree-server  | [2023-07-03 21:18:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:244)
inventree-server  | [2023-07-03 21:18:05 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:245)
inventree-server  | [2023-07-03 21:18:06 +0000] [9] [WARNING] Worker with pid 243 was terminated due to signal 9
inventree-server  | [2023-07-03 21:18:06 +0000] [9] [WARNING] Worker with pid 242 was terminated due to signal 9
inventree-server  | [2023-07-03 21:18:06 +0000] [9] [WARNING] Worker with pid 244 was terminated due to signal 9
inventree-server  | [2023-07-03 21:18:06 +0000] [9] [WARNING] Worker with pid 245 was terminated due to signal 9
inventree-proxy   | 2023/07/03 21:18:26 [error] 21#21: *23 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.165, server: , request: "GET /settings/ HTTP/1.1", upstream: "http://172.18.0.3:8000/settings/", host: "astrometerspi.lan:1337", referrer: "http://astrometerspi.lan:1337/stock/item/12/"
inventree-proxy   | 192.168.1.165 - - [03/Jul/2023:21:18:26 +0000] "GET /settings/ HTTP/1.1" 504 167 "http://astrometerspi.lan:1337/stock/item/12/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0" "-"
inventree-server  | [2023-07-03 21:18:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:457)
inventree-server  | [2023-07-03 21:18:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:459)
inventree-server  | [2023-07-03 21:18:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:460)
inventree-server  | [2023-07-03 21:18:36 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:461)

I have tried to extend timeout time in config.yaml file. But Timeout occurs in the same time. This setting (in config.yaml) has no effect on the workers timeout. Do you know, how to extend this timeout?
It seems that actual timeout is something around 30s. In config.yaml is pre-set value 90. I think that it can take longer time to install this pip plugin and satisfy all other requirements. Especially on new installations.

**Comment by roman-dvorak** [comment]
I have installed it right now from commandline and it works. It takes around 1 minute (due to dependencies). 
But it doesn't work properly (or I don't know how it should behave). I need to do deeper look to this plugin. 

Thank you for your help!

**Comment by SergeoLacruz** [comment]
I did not try it from the UI yet. will try this.  One minute is quite long. I remember it was faster here. It does not have many dependencies.Am 04.07.2023 um 21:34 schrieb Roman Dvořák ***@***.***>:﻿
I have installed it right now from commandline and it works. It takes around 1 minute (due to dependencies).
But it doesn't work properly (or I don't know how it should behave). I need to do deeper look to this plugin.
Thank you for your help!

**Comment by SergeoLacruz** [comment]
I did some trials here. 
Install plugin from command line running pip install git+https://github.com/SergeoLacruz/inventree-supplier-panel takes about 10 seconds. You need to restart the server for the plugin to appear. 
Installing the plugin from the Inventree UI takes about the same. In that case the plugin appears in the plugins.txt file. You anyhow have to restart the server after install.
